spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/agrologisticsdb
    password: ${MYSQL_ROOT_PASSWORD}
    username: ${MYSQL_ROOT_USER}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.format_sql: true
  sql:
    init:
      mode: always
server:
  port: 9080

secret:
  key: 8HHUNJRR848HON48848

price:
  cost: 1